import { CountryList } from "@/type/contact/contactUs";

export const countryList: CountryList[] = [
  {
    name: "Afghanistan",
    code: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
    dial: "+93",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Albania",
    code: "AL",
    flag: "https://flagcdn.com/w320/al.png",
    dial: "+355",
    minLength: 9,
    maxLength: 12,
  },
  {
    name: "Algeria",
    code: "DZ",
    flag: "https://flagcdn.com/w320/dz.png",
    dial: "+213",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Andorra",
    code: "AD",
    flag: "https://flagcdn.com/w320/ad.png",
    dial: "+376",
    minLength: 6,
    maxLength: 9,
  },
  {
    name: "Angola",
    code: "AO",
    flag: "https://flagcdn.com/w320/ao.png",
    dial: "+244",
    minLength: 9,
    maxLength: 12,
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    flag: "https://flagcdn.com/w320/ag.png",
    dial: "+1268",
    minLength: 10,
    maxLength: 12,
  },
  {
    name: "Argentina",
    code: "AR",
    flag: "https://flagcdn.com/w320/ar.png",
    dial: "+54",
    minLength: 10,
    maxLength: 13,
  },
  {
    name: "Armenia",
    code: "AM",
    flag: "https://flagcdn.com/w320/am.png",
    dial: "+374",
    minLength: 8,
    maxLength: 10,
  },
  {
    name: "Australia",
    code: "AU",
    flag: "https://flagcdn.com/w320/au.png",
    dial: "+61",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Austria",
    code: "AT",
    flag: "https://flagcdn.com/w320/at.png",
    dial: "+43",
    minLength: 10,
    maxLength: 13,
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    flag: "https://flagcdn.com/w320/az.png",
    dial: "+994",
    minLength: 9,
    maxLength: 12,
  },

  {
    name: "Bahamas",
    code: "BS",
    flag: "https://flagcdn.com/w320/bs.png",
    dial: "+1242",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Bahrain",
    code: "BH",
    flag: "https://flagcdn.com/w320/bh.png",
    dial: "+973",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Bangladesh",
    code: "BD",
    flag: "https://flagcdn.com/w320/bd.png",
    dial: "+880",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Barbados",
    code: "BB",
    flag: "https://flagcdn.com/w320/bb.png",
    dial: "+1246",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Belarus",
    code: "BY",
    flag: "https://flagcdn.com/w320/by.png",
    dial: "+375",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Belgium",
    code: "BE",
    flag: "https://flagcdn.com/w320/be.png",
    dial: "+32",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Belize",
    code: "BZ",
    flag: "https://flagcdn.com/w320/bz.png",
    dial: "+501",
    minLength: 7,
    maxLength: 8,
  },
  {
    name: "Benin",
    code: "BJ",
    flag: "https://flagcdn.com/w320/bj.png",
    dial: "+229",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Bhutan",
    code: "BT",
    flag: "https://flagcdn.com/w320/bt.png",
    dial: "+975",
    minLength: 7,
    maxLength: 8,
  },
  {
    name: "Bolivia",
    code: "BO",
    flag: "https://flagcdn.com/w320/bo.png",
    dial: "+591",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    flag: "https://flagcdn.com/w320/ba.png",
    dial: "+387",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Botswana",
    code: "BW",
    flag: "https://flagcdn.com/w320/bw.png",
    dial: "+267",
    minLength: 7,
    maxLength: 8,
  },
  {
    name: "Brazil",
    code: "BR",
    flag: "https://flagcdn.com/w320/br.png",
    dial: "+55",
    minLength: 10,
    maxLength: 11,
  },
  {
    name: "Brunei",
    code: "BN",
    flag: "https://flagcdn.com/w320/bn.png",
    dial: "+673",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Bulgaria",
    code: "BG",
    flag: "https://flagcdn.com/w320/bg.png",
    dial: "+359",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Burkina Faso",
    code: "BF",
    flag: "https://flagcdn.com/w320/bf.png",
    dial: "+226",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Burundi",
    code: "BI",
    flag: "https://flagcdn.com/w320/bi.png",
    dial: "+257",
    minLength: 8,
    maxLength: 8,
  },

  {
    name: "Cambodia",
    code: "KH",
    flag: "https://flagcdn.com/w320/kh.png",
    dial: "+855",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Cameroon",
    code: "CM",
    flag: "https://flagcdn.com/w320/cm.png",
    dial: "+237",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Canada",
    code: "CA",
    flag: "https://flagcdn.com/w320/ca.png",
    dial: "+1",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Cape Verde",
    code: "CV",
    flag: "https://flagcdn.com/w320/cv.png",
    dial: "+238",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Central African Republic",
    code: "CF",
    flag: "https://flagcdn.com/w320/cf.png",
    dial: "+236",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Chad",
    code: "TD",
    flag: "https://flagcdn.com/w320/td.png",
    dial: "+235",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Chile",
    code: "CL",
    flag: "https://flagcdn.com/w320/cl.png",
    dial: "+56",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "China",
    code: "CN",
    flag: "https://flagcdn.com/w320/cn.png",
    dial: "+86",
    minLength: 11,
    maxLength: 11,
  },
  {
    name: "Colombia",
    code: "CO",
    flag: "https://flagcdn.com/w320/co.png",
    dial: "+57",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Comoros",
    code: "KM",
    flag: "https://flagcdn.com/w320/km.png",
    dial: "+269",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Congo (Republic)",
    code: "CG",
    flag: "https://flagcdn.com/w320/cg.png",
    dial: "+242",
    minLength: 7,
    maxLength: 9,
  },
  {
    name: "Costa Rica",
    code: "CR",
    flag: "https://flagcdn.com/w320/cr.png",
    dial: "+506",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Croatia",
    code: "HR",
    flag: "https://flagcdn.com/w320/hr.png",
    dial: "+385",
    minLength: 8,
    maxLength: 12,
  },
  {
    name: "Cuba",
    code: "CU",
    flag: "https://flagcdn.com/w320/cu.png",
    dial: "+53",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Cyprus",
    code: "CY",
    flag: "https://flagcdn.com/w320/cy.png",
    dial: "+357",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Czechia",
    code: "CZ",
    flag: "https://flagcdn.com/w320/cz.png",
    dial: "+420",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Denmark",
    code: "DK",
    flag: "https://flagcdn.com/w320/dk.png",
    dial: "+45",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Djibouti",
    code: "DJ",
    flag: "https://flagcdn.com/w320/dj.png",
    dial: "+253",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Dominica",
    code: "DM",
    flag: "https://flagcdn.com/w320/dm.png",
    dial: "+1767",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Dominican Republic",
    code: "DO",
    flag: "https://flagcdn.com/w320/do.png",
    dial: "+1809",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "DR Congo",
    code: "CD",
    flag: "https://flagcdn.com/w320/cd.png",
    dial: "+243",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Ecuador",
    code: "EC",
    flag: "https://flagcdn.com/w320/ec.png",
    dial: "+593",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Egypt",
    code: "EG",
    flag: "https://flagcdn.com/w320/eg.png",
    dial: "+20",
    minLength: 9,
    maxLength: 11,
  },
  {
    name: "El Salvador",
    code: "SV",
    flag: "https://flagcdn.com/w320/sv.png",
    dial: "+503",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    flag: "https://flagcdn.com/w320/gq.png",
    dial: "+240",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Eritrea",
    code: "ER",
    flag: "https://flagcdn.com/w320/er.png",
    dial: "+291",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Estonia",
    code: "EE",
    flag: "https://flagcdn.com/w320/ee.png",
    dial: "+372",
    minLength: 7,
    maxLength: 8,
  },
  {
    name: "Eswatini",
    code: "SZ",
    flag: "https://flagcdn.com/w320/sz.png",
    dial: "+268",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Ethiopia",
    code: "ET",
    flag: "https://flagcdn.com/w320/et.png",
    dial: "+251",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Fiji",
    code: "FJ",
    flag: "https://flagcdn.com/w320/fj.png",
    dial: "+679",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Finland",
    code: "FI",
    flag: "https://flagcdn.com/w320/fi.png",
    dial: "+358",
    minLength: 7,
    maxLength: 12,
  },
  {
    name: "France",
    code: "FR",
    flag: "https://flagcdn.com/w320/fr.png",
    dial: "+33",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Gabon",
    code: "GA",
    flag: "https://flagcdn.com/w320/ga.png",
    dial: "+241",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Gambia",
    code: "GM",
    flag: "https://flagcdn.com/w320/gm.png",
    dial: "+220",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Georgia",
    code: "GE",
    flag: "https://flagcdn.com/w320/ge.png",
    dial: "+995",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Germany",
    code: "DE",
    flag: "https://flagcdn.com/w320/de.png",
    dial: "+49",
    minLength: 10,
    maxLength: 11,
  },
  {
    name: "Ghana",
    code: "GH",
    flag: "https://flagcdn.com/w320/gh.png",
    dial: "+233",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Greece",
    code: "GR",
    flag: "https://flagcdn.com/w320/gr.png",
    dial: "+30",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Grenada",
    code: "GD",
    flag: "https://flagcdn.com/w320/gd.png",
    dial: "+1473",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Guatemala",
    code: "GT",
    flag: "https://flagcdn.com/w320/gt.png",
    dial: "+502",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Guinea",
    code: "GN",
    flag: "https://flagcdn.com/w320/gn.png",
    dial: "+224",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    flag: "https://flagcdn.com/w320/gw.png",
    dial: "+245",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Guyana",
    code: "GY",
    flag: "https://flagcdn.com/w320/gy.png",
    dial: "+592",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Haiti",
    code: "HT",
    flag: "https://flagcdn.com/w320/ht.png",
    dial: "+509",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Honduras",
    code: "HN",
    flag: "https://flagcdn.com/w320/hn.png",
    dial: "+504",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Hungary",
    code: "HU",
    flag: "https://flagcdn.com/w320/hu.png",
    dial: "+36",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Iceland",
    code: "IS",
    flag: "https://flagcdn.com/w320/is.png",
    dial: "+354",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "India",
    code: "IN",
    flag: "https://flagcdn.com/w320/in.png",
    dial: "+91",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Indonesia",
    code: "ID",
    flag: "https://flagcdn.com/w320/id.png",
    dial: "+62",
    minLength: 9,
    maxLength: 11,
  },
  {
    name: "Iran",
    code: "IR",
    flag: "https://flagcdn.com/w320/ir.png",
    dial: "+98",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Iraq",
    code: "IQ",
    flag: "https://flagcdn.com/w320/iq.png",
    dial: "+964",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Ireland",
    code: "IE",
    flag: "https://flagcdn.com/w320/ie.png",
    dial: "+353",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Israel",
    code: "IL",
    flag: "https://flagcdn.com/w320/il.png",
    dial: "+972",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Italy",
    code: "IT",
    flag: "https://flagcdn.com/w320/it.png",
    dial: "+39",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Jamaica",
    code: "JM",
    flag: "https://flagcdn.com/w320/jm.png",
    dial: "+1876",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Japan",
    code: "JP",
    flag: "https://flagcdn.com/w320/jp.png",
    dial: "+81",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Jordan",
    code: "JO",
    flag: "https://flagcdn.com/w320/jo.png",
    dial: "+962",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    flag: "https://flagcdn.com/w320/kz.png",
    dial: "+76",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Kenya",
    code: "KE",
    flag: "https://flagcdn.com/w320/ke.png",
    dial: "+254",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Kiribati",
    code: "KI",
    flag: "https://flagcdn.com/w320/ki.png",
    dial: "+686",
    minLength: 5,
    maxLength: 5,
  },
  {
    name: "Kuwait",
    code: "KW",
    flag: "https://flagcdn.com/w320/kw.png",
    dial: "+965",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    flag: "https://flagcdn.com/w320/kg.png",
    dial: "+996",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Laos",
    code: "LA",
    flag: "https://flagcdn.com/w320/la.png",
    dial: "+856",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Latvia",
    code: "LV",
    flag: "https://flagcdn.com/w320/lv.png",
    dial: "+371",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Lebanon",
    code: "LB",
    flag: "https://flagcdn.com/w320/lb.png",
    dial: "+961",
    minLength: 7,
    maxLength: 8,
  },
  {
    name: "Lesotho",
    code: "LS",
    flag: "https://flagcdn.com/w320/ls.png",
    dial: "+266",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Liberia",
    code: "LR",
    flag: "https://flagcdn.com/w320/lr.png",
    dial: "+231",
    minLength: 7,
    maxLength: 8,
  },
  {
    name: "Libya",
    code: "LY",
    flag: "https://flagcdn.com/w320/ly.png",
    dial: "+218",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Liechtenstein",
    code: "LI",
    flag: "https://flagcdn.com/w320/li.png",
    dial: "+423",
    minLength: 7,
    maxLength: 9,
  },
  {
    name: "Lithuania",
    code: "LT",
    flag: "https://flagcdn.com/w320/lt.png",
    dial: "+370",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Luxembourg",
    code: "LU",
    flag: "https://flagcdn.com/w320/lu.png",
    dial: "+352",
    minLength: 8,
    maxLength: 11,
  },
  {
    name: "Madagascar",
    code: "MG",
    flag: "https://flagcdn.com/w320/mg.png",
    dial: "+261",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Malawi",
    code: "MW",
    flag: "https://flagcdn.com/w320/mw.png",
    dial: "+265",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Malaysia",
    code: "MY",
    flag: "https://flagcdn.com/w320/my.png",
    dial: "+60",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Maldives",
    code: "MV",
    flag: "https://flagcdn.com/w320/mv.png",
    dial: "+960",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Mali",
    code: "ML",
    flag: "https://flagcdn.com/w320/ml.png",
    dial: "+223",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Malta",
    code: "MT",
    flag: "https://flagcdn.com/w320/mt.png",
    dial: "+356",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Marshall Islands",
    code: "MH",
    flag: "https://flagcdn.com/w320/mh.png",
    dial: "+692",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Mauritania",
    code: "MR",
    flag: "https://flagcdn.com/w320/mr.png",
    dial: "+222",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Mauritius",
    code: "MU",
    flag: "https://flagcdn.com/w320/mu.png",
    dial: "+230",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Mexico",
    code: "MX",
    flag: "https://flagcdn.com/w320/mx.png",
    dial: "+52",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Micronesia",
    code: "FM",
    flag: "https://flagcdn.com/w320/fm.png",
    dial: "+691",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Moldova",
    code: "MD",
    flag: "https://flagcdn.com/w320/md.png",
    dial: "+373",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Monaco",
    code: "MC",
    flag: "https://flagcdn.com/w320/mc.png",
    dial: "+377",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Mongolia",
    code: "MN",
    flag: "https://flagcdn.com/w320/mn.png",
    dial: "+976",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Montenegro",
    code: "ME",
    flag: "https://flagcdn.com/w320/me.png",
    dial: "+382",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Morocco",
    code: "MA",
    flag: "https://flagcdn.com/w320/ma.png",
    dial: "+212",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Mozambique",
    code: "MZ",
    flag: "https://flagcdn.com/w320/mz.png",
    dial: "+258",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Myanmar",
    code: "MM",
    flag: "https://flagcdn.com/w320/mm.png",
    dial: "+95",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Namibia",
    code: "NA",
    flag: "https://flagcdn.com/w320/na.png",
    dial: "+264",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Nauru",
    code: "NR",
    flag: "https://flagcdn.com/w320/nr.png",
    dial: "+674",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Nepal",
    code: "NP",
    flag: "https://flagcdn.com/w320/np.png",
    dial: "+977",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Netherlands",
    code: "NL",
    flag: "https://flagcdn.com/w320/nl.png",
    dial: "+31",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "New Zealand",
    code: "NZ",
    flag: "https://flagcdn.com/w320/nz.png",
    dial: "+64",
    minLength: 8,
    maxLength: 10,
  },
  {
    name: "Nicaragua",
    code: "NI",
    flag: "https://flagcdn.com/w320/ni.png",
    dial: "+505",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Niger",
    code: "NE",
    flag: "https://flagcdn.com/w320/ne.png",
    dial: "+227",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Nigeria",
    code: "NG",
    flag: "https://flagcdn.com/w320/ng.png",
    dial: "+234",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "North Korea",
    code: "KP",
    flag: "https://flagcdn.com/w320/kp.png",
    dial: "+850",
    minLength: 9,
    maxLength: 12,
  },
  {
    name: "North Macedonia",
    code: "MK",
    flag: "https://flagcdn.com/w320/mk.png",
    dial: "+389",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Norway",
    code: "NO",
    flag: "https://flagcdn.com/w320/no.png",
    dial: "+47",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Oman",
    code: "OM",
    flag: "https://flagcdn.com/w320/om.png",
    dial: "+968",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Pakistan",
    code: "PK",
    flag: "https://flagcdn.com/w320/pk.png",
    dial: "+92",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Palau",
    code: "PW",
    flag: "https://flagcdn.com/w320/pw.png",
    dial: "+680",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Panama",
    code: "PA",
    flag: "https://flagcdn.com/w320/pa.png",
    dial: "+507",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    flag: "https://flagcdn.com/w320/pg.png",
    dial: "+675",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Paraguay",
    code: "PY",
    flag: "https://flagcdn.com/w320/py.png",
    dial: "+595",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Peru",
    code: "PE",
    flag: "https://flagcdn.com/w320/pe.png",
    dial: "+51",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Philippines",
    code: "PH",
    flag: "https://flagcdn.com/w320/ph.png",
    dial: "+63",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Poland",
    code: "PL",
    flag: "https://flagcdn.com/w320/pl.png",
    dial: "+48",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Portugal",
    code: "PT",
    flag: "https://flagcdn.com/w320/pt.png",
    dial: "+351",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Qatar",
    code: "QA",
    flag: "https://flagcdn.com/w320/qa.png",
    dial: "+974",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Romania",
    code: "RO",
    flag: "https://flagcdn.com/w320/ro.png",
    dial: "+40",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Russia",
    code: "RU",
    flag: "https://flagcdn.com/w320/ru.png",
    dial: "+73",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Rwanda",
    code: "RW",
    flag: "https://flagcdn.com/w320/rw.png",
    dial: "+250",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    flag: "https://flagcdn.com/w320/kn.png",
    dial: "+1869",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Saint Lucia",
    code: "LC",
    flag: "https://flagcdn.com/w320/lc.png",
    dial: "+1758",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    flag: "https://flagcdn.com/w320/vc.png",
    dial: "+1784",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Samoa",
    code: "WS",
    flag: "https://flagcdn.com/w320/ws.png",
    dial: "+685",
    minLength: 5,
    maxLength: 7,
  },
  {
    name: "San Marino",
    code: "SM",
    flag: "https://flagcdn.com/w320/sm.png",
    dial: "+378",
    minLength: 8,
    maxLength: 10,
  },
  {
    name: "São Tomé and Príncipe",
    code: "ST",
    flag: "https://flagcdn.com/w320/st.png",
    dial: "+239",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    flag: "https://flagcdn.com/w320/sa.png",
    dial: "+966",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Senegal",
    code: "SN",
    flag: "https://flagcdn.com/w320/sn.png",
    dial: "+221",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Serbia",
    code: "RS",
    flag: "https://flagcdn.com/w320/rs.png",
    dial: "+381",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Seychelles",
    code: "SC",
    flag: "https://flagcdn.com/w320/sc.png",
    dial: "+248",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Sierra Leone",
    code: "SL",
    flag: "https://flagcdn.com/w320/sl.png",
    dial: "+232",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Singapore",
    code: "SG",
    flag: "https://flagcdn.com/w320/sg.png",
    dial: "+65",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Slovakia",
    code: "SK",
    flag: "https://flagcdn.com/w320/sk.png",
    dial: "+421",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Slovenia",
    code: "SI",
    flag: "https://flagcdn.com/w320/si.png",
    dial: "+386",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Solomon Islands",
    code: "SB",
    flag: "https://flagcdn.com/w320/sb.png",
    dial: "+677",
    minLength: 5,
    maxLength: 7,
  },
  {
    name: "Somalia",
    code: "SO",
    flag: "https://flagcdn.com/w320/so.png",
    dial: "+252",
    minLength: 8,
    maxLength: 11,
  },
  {
    name: "South Africa",
    code: "ZA",
    flag: "https://flagcdn.com/w320/za.png",
    dial: "+27",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "South Korea",
    code: "KR",
    flag: "https://flagcdn.com/w320/kr.png",
    dial: "+82",
    minLength: 9,
    maxLength: 11,
  },
  {
    name: "South Sudan",
    code: "SS",
    flag: "https://flagcdn.com/w320/ss.png",
    dial: "+211",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Spain",
    code: "ES",
    flag: "https://flagcdn.com/w320/es.png",
    dial: "+34",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Sri Lanka",
    code: "LK",
    flag: "https://flagcdn.com/w320/lk.png",
    dial: "+94",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Sudan",
    code: "SD",
    flag: "https://flagcdn.com/w320/sd.png",
    dial: "+249",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Suriname",
    code: "SR",
    flag: "https://flagcdn.com/w320/sr.png",
    dial: "+597",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Sweden",
    code: "SE",
    flag: "https://flagcdn.com/w320/se.png",
    dial: "+46",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Switzerland",
    code: "CH",
    flag: "https://flagcdn.com/w320/ch.png",
    dial: "+41",
    minLength: 9,
    maxLength: 12,
  },
  {
    name: "Syria",
    code: "SY",
    flag: "https://flagcdn.com/w320/sy.png",
    dial: "+963",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Taiwan",
    code: "TW",
    flag: "https://flagcdn.com/w320/tw.png",
    dial: "+886",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Tajikistan",
    code: "TJ",
    flag: "https://flagcdn.com/w320/tj.png",
    dial: "+992",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Tanzania",
    code: "TZ",
    flag: "https://flagcdn.com/w320/tz.png",
    dial: "+255",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Thailand",
    code: "TH",
    flag: "https://flagcdn.com/w320/th.png",
    dial: "+66",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Timor-Leste",
    code: "TL",
    flag: "https://flagcdn.com/w320/tl.png",
    dial: "+670",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Togo",
    code: "TG",
    flag: "https://flagcdn.com/w320/tg.png",
    dial: "+228",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Tonga",
    code: "TO",
    flag: "https://flagcdn.com/w320/to.png",
    dial: "+676",
    minLength: 5,
    maxLength: 7,
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    flag: "https://flagcdn.com/w320/tt.png",
    dial: "+1868",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Tunisia",
    code: "TN",
    flag: "https://flagcdn.com/w320/tn.png",
    dial: "+216",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Turkey",
    code: "TR",
    flag: "https://flagcdn.com/w320/tr.png",
    dial: "+90",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Turkmenistan",
    code: "TM",
    flag: "https://flagcdn.com/w320/tm.png",
    dial: "+993",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Tuvalu",
    code: "TV",
    flag: "https://flagcdn.com/w320/tv.png",
    dial: "+688",
    minLength: 5,
    maxLength: 5,
  },
  {
    name: "Uganda",
    code: "UG",
    flag: "https://flagcdn.com/w320/ug.png",
    dial: "+256",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Ukraine",
    code: "UA",
    flag: "https://flagcdn.com/w320/ua.png",
    dial: "+380",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    flag: "https://flagcdn.com/w320/ae.png",
    dial: "+971",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "United Kingdom",
    code: "GB",
    flag: "https://flagcdn.com/w320/gb.png",
    dial: "+44",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "United States",
    code: "US",
    flag: "https://flagcdn.com/w320/us.png",
    dial: "+1",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Uruguay",
    code: "UY",
    flag: "https://flagcdn.com/w320/uy.png",
    dial: "+598",
    minLength: 8,
    maxLength: 9,
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    flag: "https://flagcdn.com/w320/uz.png",
    dial: "+998",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Vanuatu",
    code: "VU",
    flag: "https://flagcdn.com/w320/vu.png",
    dial: "+678",
    minLength: 5,
    maxLength: 7,
  },
  {
    name: "Vatican City",
    code: "VA",
    flag: "https://flagcdn.com/w320/va.png",
    dial: "+3906698",
    minLength: 6,
    maxLength: 12,
  },
  {
    name: "Venezuela",
    code: "VE",
    flag: "https://flagcdn.com/w320/ve.png",
    dial: "+58",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Vietnam",
    code: "VN",
    flag: "https://flagcdn.com/w320/vn.png",
    dial: "+84",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Yemen",
    code: "YE",
    flag: "https://flagcdn.com/w320/ye.png",
    dial: "+967",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Zambia",
    code: "ZM",
    flag: "https://flagcdn.com/w320/zm.png",
    dial: "+260",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    flag: "https://flagcdn.com/w320/zw.png",
    dial: "+263",
    minLength: 9,
    maxLength: 9,
  },
];
